### ISSUE TITLE
Recerca d'equips

### ISSUE THREAD

**Issue by jciberta** [jciberta/ingest#11]
Afegir el correu a la recerca d'equips

**Comment by EsteveGR** [comment]
Vols dir afegir el mail del coordinador aqui?

![image](https://user-images.githubusercontent.com/15687101/226590881-2a1655e5-cba8-4fdf-afb8-78fae0828cfa.png)

**Comment by EsteveGR** [comment]
FET! tens PR.

**Comment by jciberta** [comment]
Perfecte!
