### ISSUE TITLE
Assignació UF per part del cap de departament

### ISSUE THREAD

**Issue by jciberta** [jciberta/ingest#27]
### Descriviu el problema

Cap de departament ha d'assignar les UF als professors

### Descriviu la solució proposada

A l'escriptori dels caps de departament ha d'aparèixer una nova targeta per fer aquesta tasca

### Heu comprovat si ja s'ha plantejat aquest problema?

- [X] No he trobat cap problema semblant

**Comment by EsteveGR** [comment]
Fet!

**Comment by jciberta** [comment]
Fet!
